[project]
name = "pytpo"
version = "0.1.1"
description = "A simple custom IDE."
requires-python = ">=3.11"
dependencies = [
    "pyside6",
    "pyte",
    "ruff",
    "pyflakes",
    "jedi",
    "markdown",
    "pygments",
    "pymdown-extensions",
]
